apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom-autoscaler.fullname" . }}
  labels: {{ include "custom-autoscaler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "custom-autoscaler.fullname" . }}
