spring:
  application:
    name: custom-autoscaler

server:
  port: 8080

logging:
  level:
    root: INFO

prometheus:
  base-url: "http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090"
  namespace: "default"
  scaled-deployment: "task-service"